Repository 2-2-22/rolling, pull requests merged in 2024-03, with the labels that each got.

#30 [Feat] button 컴포넌트 제작
  src/components/Button/Button/Button.jsx
  src/components/Button/Button/Button.module.scss
  src/components/Button/ButtonArrow/ButtonArrow.jsx
  src/components/Button/ButtonArrow/ButtonArrow.module.scss
  src/components/Button/ButtonPlus/ButtonPlus.jsx
  src/components/Button/ButtonPlus/ButtonPlus.module.scss
  src/components/Button/ButtonToggle/ButtonToggle.jsx
  src/components/Button/ButtonToggle/ButtonToggle.module.scss
  src/components/Button/index.js
  src/constants/button.js
Labels: Feat

#34 [feat] text field 제작
  package-lock.json
  package.json
  src/App.jsx
  src/assets/images/add-20.svg
  src/assets/images/add-24.svg
  src/assets/images/arrow_down.svg
  src/assets/images/arrow_left.svg
  src/assets/images/arrow_right.svg
  src/assets/images/check.svg
  src/assets/images/deleted.svg
  src/assets/images/dots-edit.svg
  src/assets/images/logo.svg
  src/assets/images/plus.svg
  src/assets/images/share-20.svg
  src/assets/images/share-24.svg
  src/assets/svg/Add20.jsx
  src/assets/svg/Add24.jsx
  src/assets/svg/ArrowDown.jsx
  src/assets/svg/ArrowLeft.jsx
  src/assets/svg/ArrowRight.jsx
  src/assets/svg/ArrowUp.jsx
  src/assets/svg/Check.jsx
  src/assets/svg/Deleted.jsx
  src/assets/svg/DotsEdit.jsx
  src/assets/svg/Logo.jsx
  src/assets/svg/Plus.jsx
  src/assets/svg/Share20.jsx
  src/assets/svg/Share24.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Dropdown/index.js
  src/components/Input/Input.jsx
  src/components/Input/Input.module.scss
  src/components/Input/index.js
  src/components/ReactDraft/ReactDraft.jsx
  src/components/ReactDraft/ReactDraft.module.scss
  src/components/ReactDraft/index.js
  src/components/tinymce/index.jsx
  src/hooks/useManageDropdown/useManageDropdown.js
  src/hooks/useManageInput/useManageInput.js
  src/styles/fonts.scss
  src/styles/reset.scss
  vite.config.js
Labels: Feat

#33 29 feat toast 컴포넌트 생성
  src/assets/images/close.svg
  src/assets/images/completed.svg
  src/components/Header/Header.jsx
  src/components/Header/index.js
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.module.scss
  src/components/Toast/index.js
Labels: Feat

#36 [Feat] Modal 제작(기능만 구현)
  index.html
  src/components/Modal/common/Modal.jsx
  src/components/Modal/common/ModalLayout.jsx
  src/components/Modal/common/ModalLayout.module.scss
  src/components/Modal/common/ModalPortal.jsx
  src/components/Modal/common/index.js
  src/components/Modal/index.js
  src/contexts/Modal/ModalContext.jsx
  src/contexts/index.js
  src/hooks/useClickOutside.js
  src/hooks/useModal.js
  src/main.jsx
Labels: Feat

#37 22 feat card list component 제작
  package-lock.json
  src/App.jsx
  src/assets/svg/Add20.jsx
  src/assets/svg/Add24.jsx
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.module.scss
  src/components/CardList/CardOverview.jsx
  src/components/CardList/CardOverview.module.scss
  src/components/CardList/Reactions.jsx
  src/components/CardList/Reactions.module.scss
  src/components/ReactDraft/ReactDraft.jsx
  src/components/tinymce/index.jsx
  src/hooks/useFetch.js
  src/pages/listpage/ListPage.jsx
  src/pages/listpage/ListPage.module.scss
  src/styles/reset.scss
Labels: Feat

#40 [Refactor] button 컴포넌트에 svg icon 추가
  src/components/Button/ButtonArrow/ButtonArrow.jsx
  src/components/Button/ButtonPlus/ButtonPlus.jsx
  src/constants/button.js
Labels: Refactor

#47 [Feat] Avatar 컴포넌트 제작
  src/assets/images/avatar-default.png
  src/components/Avatar/Avartar.jsx
  src/components/Avatar/Avatar.module.scss
  src/components/Avatar/index.js
Labels: Feat

#50 [refactor] text field 리팩토링
  package-lock.json
  src/App.jsx
  src/components/CardList/CardList.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.scss
  src/components/Header/Header.jsx
  src/components/Header/index.js
  src/components/Input/Input.jsx
  src/components/Input/Input.module.scss
  src/components/ReactDraft/ReactDraft.jsx
  src/components/tinymce/index.jsx
  src/hooks/useManageDropdown/useManageDropdown.js
  src/hooks/useManageInput/useManageInput.js
  src/pages/layout/index.jsx
  src/pages/listpage/ListPage.jsx
  src/pages/postpage/index.jsx
Labels: Refactor

#54 [Refactor] card 컴포넌트 리팩토링
  src/components/Card/Card.jsx
  src/components/Card/Card.module.scss
  src/components/CardPost/Card.jsx
  src/components/CardPost/CardEdit.jsx
  src/components/CardPost/CardPlus.jsx
  src/components/CardPost/CardPost.jsx
  src/components/CardPost/CardPost.module.scss
Labels: Refactor

#49 [Feat] Modal 컴포넌트 추가 작업
  src/components/Badge/BadgeRelation.jsx
  src/components/Badge/BadgeRelation.module.scss
  src/components/Badge/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalCardInfo/ModalCardInfo.jsx
  src/components/Modal/ModalCardInfo/ModalCardInfo.module.scss
  src/components/Modal/ModalConfirm/ModalConfirm.jsx
  src/components/Modal/ModalConfirm/ModalConfirm.module.scss
  src/components/Modal/common/Modal.jsx
  src/components/Modal/common/ModalLayout.jsx
  src/components/Modal/common/ModalPortal.jsx
  src/components/Modal/common/index.js
  src/components/Modal/index.js
  src/contexts/Modal/ModalContext.jsx
  src/hooks/useModal.js
  src/main.jsx
  src/utils/dateFormatter.js
Labels: Feat

#52 [Refactor] Button 컴포넌트 리팩토링
  src/components/Button/Button/Button.jsx
  src/components/Button/Button/Button.module.scss
  src/components/Button/ButtonArrow/ButtonArrow.jsx
  src/components/Button/ButtonPlus/ButtonPlus.jsx
  src/constants/button.js
Labels: Refactor

#56 [Feat] ListPage 제작 - 미완성
  package-lock.json
  src/App.jsx
  src/components/CardList/CardList.jsx
  src/components/CardList/CardList.module.scss
  src/components/CardList/CardOverview.jsx
  src/components/CardList/CardOverview.module.scss
  src/components/CardList/Reactions.jsx
  src/components/CardList/Reactions.module.scss
  src/hooks/useFetch.js
  src/pages/LoadingPage/LoadingPage.jsx
  src/pages/LoadingPage/LoadingPage.module.scss
  src/pages/layout/index.jsx
  src/pages/listpage/ListPage.jsx
  src/pages/listpage/ListPage.module.scss
Labels: Feat

#58 [Feat] {페어} CardPostList 페이지 제작
  src/components/CardPost/Card.jsx
  src/components/CardPost/CardEdit.jsx
  src/components/CardPost/CardPost.module.scss
  src/pages/CardPostListPage/CardPostListPage.jsx
  src/pages/CardPostListPage/CardPostListPage.module.scss
Labels: Feat

#60 [Feat] Header(미완)
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.module.scss
  src/components/Header/SubHeader/index.js
  src/utils/handleShareKakao.js
  src/utils/index.js
  vite.config.js.timestamp-1709298674126-733f0ca23ddcd.mjs
Labels: Refactor

#61 [Refactor] merge 이후 conflict 해결
  src/App.jsx
  src/components/Button/ButtonToggle/ButtonToggle.jsx
  src/components/Button/index.js
  src/components/Header/Header.jsx
  src/pages/CardPostListPage/index.js
  src/pages/LandingPage.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/LandingPage/index.js
  src/pages/Layout/Layout.jsx
  src/pages/Layout/index.js
  src/pages/LoadingPage/index.js
  src/pages/PostMessagePage/index.js
  src/pages/index.js
  src/pages/listpage/index.js
  src/pages/listpage/index.jsx
  src/pages/postpage/PostPage.jsx
  src/pages/postpage/index.js
Labels: Refactor

#63 [Refactor] ButtonToggle 누락된 작업 진행
  src/components/Button/ButtonToggle/ButtonToggle.jsx
  src/components/Button/index.js
Labels: Refactor

#66 [Refactor] ButtonArrow 배경 흐림도 opacity 추가
  src/components/Button/ButtonArrow/ButtonArrow.module.scss
Labels: Refactor

#65 feat landing page 생성
  src/assets/images/landing1.png
  src/assets/images/landing2.png
  src/components/Header/Header.jsx
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/index.js
  src/pages/LandingPage/Landing.module.scss
  src/pages/LandingPage/LandingPage.jsx
  src/pages/Layout/Layout.jsx
  src/pages/LoadingPage/LoadingPage.jsx
  src/pages/postpage/PostPage.jsx
Labels: Feat

#67 [Feat] {페어} CardPostList 페이지 제작
  src/App.jsx
  src/components/CardPost/Card.jsx
  src/components/CardPost/CardPlus.jsx
  src/components/CardPost/CardPost.jsx
  src/components/CardPost/CardPostList.jsx
  src/components/CardPost/CardPostList.module.scss
  src/pages/CardPostListPage/CardPostListPage.jsx
Labels: Feat

#68 [Feat] header 컴포넌트 생성
  package-lock.json
  package.json
  src/components/Header/SubHeader/AddEmoziBtn.jsx
  src/components/Header/SubHeader/AddEmoziBtn.module.scss
  src/components/Header/SubHeader/EmoziToggleBox.jsx
  src/components/Header/SubHeader/EmoziToggleBox.module.scss
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.module.scss
  src/hooks/useFetch.js
Labels: Feat

#69 [feat] post page 제작
  src/App.jsx
  src/assets/images/profile1.jpg
  src/assets/images/profile2.png
  src/assets/images/profile3.png
  src/assets/images/profile4.png
  src/components/Avatar/Avartar.jsx
  src/components/CardList/CardOverview.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.module.scss
  src/components/Option/Option.jsx
  src/components/Option/Option.module.scss
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/ProfileImage/index.js
  src/components/ReactDraft/ReactDraft.jsx
  src/constants/index.js
  src/hooks/useManageDropdown/useManageDropdown.js
  src/hooks/useManageInput/useManageInput.js
  src/pages/PostCardPage/Post.module.scss
  src/pages/PostCardPage/PostPage.jsx
  src/pages/PostCardPage/index.js
  src/pages/PostMessagePage/PostMessagePage.jsx
  src/pages/postpage/Post.module.scss
  src/pages/postpage/PostPage.jsx
  src/utils/getPostfetch.js
Labels: Feat

#76 [Refactor] Modal 리팩토링
  src/components/Modal/ModalCardInfo/ModalCardInfo.jsx
  src/components/Modal/ModalCardInfo/ModalCardInfo.module.scss
  src/components/Modal/ModalConfirm/ModalConfirm.jsx
Labels: Refactor

#72 [Refactor] Landing Page PR 수정사항 반영
  src/components/Header/Header.jsx
  src/pages/LandingPage/LandingPage.jsx
Labels: Refactor

#78 [Refactor] Button 사이즈별 width 주는 선택자 우선순위 낮춤
  src/components/Button/Button/Button.module.scss
Labels: Refactor

#74 [Refactor] post card page post message page 리팩토링
  package-lock.json
  package.json
  src/App.jsx
  src/components/Avatar/Avartar.jsx
  src/components/Option/Option.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ReactDraft/ReactDraft.jsx
  src/constants/index.js
  src/hooks/useMutate.js
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/PostCardPage/PostCardPage.jsx
  src/pages/PostCardPage/PostCardPage.module.scss
  src/pages/PostCardPage/index.js
  src/pages/PostMessagePage/PostMessagePage.jsx
  src/utils/isFunction.js
Labels: Refactor

#79 [Feat] header 기능 구현 마무리
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/SubHeader/AddEmoziBtn.jsx
  src/components/Header/SubHeader/AddEmoziBtn.module.scss
  src/components/Header/SubHeader/EmoziToggleBox.jsx
  src/components/Header/SubHeader/ShareToggleBtn.jsx
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.module.scss
  src/components/Reactions/Reactions.jsx
  src/components/Reactions/Reactions.module.scss
  src/components/Reactions/index.js
  src/hooks/useMutate.js
Labels: Feat

#82 style: 주석 해제
  src/components/Header/Header.jsx
Labels: Refactor

#83 [Refactor] Button size CSS 리팩토링
  src/components/Button/Button/Button.module.scss
Labels: Refactor

#85 [refactor] listpage 제작 - 미완성
  src/components/CardList/CardOverview/CardOverview.jsx
  src/components/CardList/CardOverview/CardOverview.module.scss
  src/components/CardList/Carousel/Carousel.jsx
  src/components/CardList/Carousel/Carousel.module.scss
  src/components/CardList/EmblaCarousel/EmblaCarousel.jsx
  src/components/CardList/EmblaCarousel/EmblaCarousel.module.scss
  src/components/CardList/EmblaCarousel/EmblaCarouselArrowButtons.jsx
  src/components/CardList/Reactions.jsx
  src/components/CardList/Reactions.module.scss
  src/components/CardList/TotalCardList/TotalCardList.jsx
  src/components/CardList/TotalCardList/TotalCardList.module.scss
  src/components/CardList/index.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.module.scss
  src/pages/ListPage/index.js
  src/pages/listpage/ListPage.jsx
  src/pages/postpage/PostPage.jsx
Labels: Refactor

#86 [Refactor] 리뷰 사항 리팩토링
  src/components/Dropdown/Dropdown.module.scss
  src/components/EnterNameInput/EnterNameInput.jsx
  src/components/EnterNameInput/EnterNameInput.module.scss
  src/components/EnterNameInput/index.js
  src/components/Input/Input.jsx
  src/components/Input/index.js
  src/components/Option/Option.module.scss
  src/components/Option/OptionPicker.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/ProfileImage/ProfileImage.module.scss
  src/constants/index.js
  src/hooks/useManageInput/useManageInput.js
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.module.scss
  src/pages/PostCardPage/PostCardPage.jsx
  src/pages/PostCardPage/PostCardPage.module.scss
  src/pages/PostMessagePage/PostMessagePage.jsx
  src/pages/PostMessagePage/PostMessagePage.module.scss
  src/styles/mixin.scss
  src/styles/reset.scss
Labels: Refactor

#87 [Feat] header 기능 구현 마무리
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/SubHeader/AddEmojiBox.jsx
  src/components/Header/SubHeader/AddEmojiBtn.jsx
  src/components/Header/SubHeader/AddEmojiBtn.module.scss
  src/components/Header/SubHeader/AddEmoziBtn.jsx
  src/components/Header/SubHeader/EmoziToggleBox.jsx
  src/components/Header/SubHeader/ShareBtn.jsx
  src/components/Header/SubHeader/ShowEmojiBox.jsx
  src/components/Header/SubHeader/ShowEmojiBox.module.scss
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.module.scss
  src/pages/LandingPage/Landing.module.scss
  vite.config.js.timestamp-1709298674126-733f0ca23ddcd.mjs
Labels: Refactor

#92 [feat] listpage 제작
  src/components/CardList/CardOverview/CardOverview.jsx
  src/components/CardList/CardOverview/CardOverview.module.scss
  src/components/CardList/EmblaCarousel/EmblaCarousel.jsx
  src/components/CardList/EmblaCarousel/EmblaCarousel.module.scss
  src/components/CardList/EmblaCarousel/EmblaCarouselArrowButtons.jsx
  src/components/CardList/TotalCardList/TotalCardList.jsx
  src/components/CardList/TotalCardList/TotalCardList.module.scss
  src/components/Reactions/Reactions.module.scss
  src/pages/ListPage/ListPage.jsx
  src/pages/ListPage/ListPage.module.scss
Labels: Feat, Refactor

#91 [Refactor] 전체적인 리팩토링 진행
  src/App.jsx
  src/api/index.js
  src/api/mockdatas/background-images.json
  src/api/mockdatas/profile-images.json
  src/components/Button/ButtonToggle/ButtonToggle.jsx
  src/components/Modal/Modal.module.scss
  src/components/Modal/ModalCardInfo/ModalCardInfo.jsx
  src/components/Modal/ModalCardInfo/ModalCardInfo.module.scss
  src/components/Modal/ModalConfirm/ModalConfirm.jsx
  src/components/index.js
  src/constants/index.js
  src/contexts/index.js
  src/hooks/useClickOutside.js
  src/pages/CardPostListPage/CardPostListEditPage.jsx
  src/pages/CardPostListPage/index.js
  src/styles/fonts.scss
Labels: Refactor

#94 [Refactor] CardPostList 페이지 제작 리팩토링 Refactor
  src/components/CardPost/CardPost.jsx
  src/components/CardPost/CardPostList.module.scss
  src/pages/CardPostListPage/CardPostListPage.jsx
  src/pages/CardPostListPage/CardPostListPage.module.scss
Labels: Refactor

#93 73 feat header 기능 구현 마무리
  src/components/Header/Header.module.scss
  src/components/Header/SubHeader/AddEmojiBox.jsx
  src/components/Header/SubHeader/AddEmojiBtn.jsx
  src/components/Header/SubHeader/AddEmojiBtn.module.scss
  src/components/Header/SubHeader/ShowEmojiBox.jsx
  src/components/Header/SubHeader/ShowEmojiBox.module.scss
  src/components/Header/SubHeader/SubHeader.jsx
  src/components/Header/SubHeader/SubHeader.module.scss
  src/components/LoadingComponent/LoadingEmojiBox.jsx
  src/components/LoadingComponent/LoadingEmojiBox.module.scss
  src/components/LoadingComponent/LoadingHeader.jsx
  src/components/LoadingComponent/LoadingHeader.module.scss
  src/components/Toast/Toast.module.scss
Labels: Refactor

#104 [bug] 머지 버그 수정
  src/App.jsx
  src/assets/images/errorPage.png
  src/pages/ErrorPage/ErrorPage.jsx
  src/pages/ErrorPage/ErrorPage.module.scss
  src/pages/ErrorPage/index.js
  src/pages/PostCardPage/PostCardPage.jsx
  src/pages/PostMessagePage/PostMessagePage.jsx
Labels: Bug

#105 [Refactor] CardPostList 페이지 제작 리팩토링 Refactor
  src/components/CardPost/CardPostList.module.scss
  src/pages/CardPostListPage/CardPostListEditPage.jsx
  src/pages/CardPostListPage/CardPostListPage.module.scss
Labels: Refactor

#111 [Refactor] observerRef를 inline style에서 className으로 변경
  src/pages/CardPostListPage/CardPostListEditPage.jsx
Labels: Refactor

#110 [Feat] title명 meta 데이터 추가
  package-lock.json
  package.json
  src/App.jsx
  src/assets/favicon/favicon.ico
  src/assets/images/logo.png
  src/main.jsx
  src/pages/CardPostListPage/CardPostListPage.jsx
  src/pages/LandingPage/LandingPage.jsx
  src/pages/ListPage/ListPage.jsx
  src/pages/PostCardPage/PostCardPage.jsx
  src/pages/PostMessagePage/PostMessagePage.jsx
  src/utils/MetaTag.jsx
Labels: Feat

#113 [refactor] 리뷰 사항 반영
  src/components/Option/Option.jsx
  src/components/Option/Option.module.scss
  src/components/ProfileImage/ProfileImage.module.scss
  src/components/ReactDraft/ReactDraft.module.scss
  src/constants/index.js
  src/pages/PostCardPage/PostCardPage.jsx
  src/pages/PostCardPage/PostCardPage.module.scss
  src/pages/PostMessagePage/PostMessagePage.jsx
  src/pages/PostMessagePage/PostMessagePage.module.scss
  src/styles/reset.scss
Labels: Refactor

#114 [Refactor] landing page 반응형 작업
  src/components/Header/Header.jsx
  src/components/Header/SubHeader/AddEmojiBtn.module.scss
  src/components/Header/SubHeader/SubHeader.module.scss
  src/components/Toast/Toast.module.scss
  src/pages/LandingPage/Landing.module.scss
  src/pages/LandingPage/LandingPage.jsx
Labels: Refactor

#115 [refactor] overview background 수정 및 여러가지 이슈 처리
  src/assets/svg/BeigeBgPattern.svg
  src/assets/svg/BlueBgPattern.svg
  src/assets/svg/GreenBgPattern.svg
  src/assets/svg/PurpleBgPattern.svg
  src/components/CardList/CardOverview/CardOverview.module.scss
  src/components/CardPost/CardPost.jsx
  src/components/CardPost/CardPostList.module.scss
  src/pages/CardPostListPage/CardPostListEditPage.jsx
  src/pages/CardPostListPage/CardPostListPage.jsx
  src/pages/CardPostListPage/CardPostListPage.module.scss
  src/pages/ListPage/ListPage.jsx
Labels: Refactor

#116 [style] style: padding 수정
  src/pages/ListPage/ListPage.module.scss
Labels: Refactor

#117 Update README.md
  README.md
Labels: Feat

#120 [refactor] 리뷰 사항 반영
  src/styles/reset.scss
Labels: Refactor

#121 Update README.md
  README.md
Labels: Refactor
